### ISSUE TITLE
move all screenshots to archive upload server

### ISSUE THREAD

**Issue by Tanza3D** [osu-archive/web#12]
@ILuvSkins @SakuruWasTaken can one of you two do this? i've got shit tons to do already lol

**Comment by oijdfdg** [comment]
Perhaps this enhancement is still yet to come. I'm waiting for it.

**Comment by SakuruWasTaken** [comment]
fuck off @rosenishere

**Comment by oijdfdg** [comment]
what did he say doe

**Comment by oijdfdg** [comment]
uh oh php hypertext preprocessor

**Comment by Tanza3D** [comment]
done, will be released with eclipse
